## Assignment 2

Que:1. Explain the difference between a Python list and a NumPy array in terms of :
- Memory Usage
- Performance

Then, write a program that creates both and performs element-wise multiplication.

Answer: 

**On the Basis of Memory Usage:**

*Python List:* Stores elements as objects and can hold different data types. Because each element stores extra metadata, it uses more memory.

*NumPy Array:* Stores elements of the same data type in contiguous memory. Due to efficient storage, it uses less memory than Python lists.

**On the Basis of Performance:**

*Python List :* Slower because it requires loops for operations and stores elements as objects.

*NumPy Array :* Faster because it uses vectorization and efficient memory management.


| Feature        | Python List | NumPy Array |
|---------------|------------|-------------|
| Data Type     | Can store different data types | Stores only same data type |
| Memory Usage  | Uses more memory | Uses less memory |
| Storage       | Stores elements as objects | Stores elements in contiguous memory |
| Performance   | Slower for numerical operations | Faster due to vectorization |


In [2]:
#A program that creates both and performs element-wise multiplication.
import numpy as np


lst = [1, 2, 3, 4, 5] # Create a Python list
arr = np.array([1, 2, 3, 4, 5]) # Create a NumPy array


lst = [x * 2 for x in lst] #element-wise multiplication
print("Python list result:", lst) 


arr = arr * 2 #element-wise multiplication
print("NumPy array result:", arr) 

Python list result: [2, 4, 6, 8, 10]
NumPy array result: [ 2  4  6  8 10]


Que:2. What is broadcasting in NumPy?

Create a 3×3 NumPy array and add a 1D array to it using broadcasting. 

Explain how NumPy applies the operation internally.

Answer: 

**Broadcasting in NumPy :** 
Broadcasting is a NumPy mechanism that allows operations between arrays of different shapes. It automatically expands the smaller array to match dimensions and performs efficient element-wise operations without copying data.


**Working of Broadcasting using 3x3 array:**

*Step:1* 
array A of 3x3 A
  = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]


Creating a 1D array B
     = [[10, 20, 30]]

*Step:2* NumPy virtually repeats B for each row of A

       [[10, 20, 30],
        [10, 20, 30],
        [10, 20, 30]]

*Step:3* At last, element-wise addition
      = [[ 1+10, 2+20, 3+30],
         [ 4+10, 5+20, 6+30],
         [ 7+10, 8+20, 9+30]]

       = [[11, 22, 33],
          [14, 25, 36],
          [17, 28, 39]]

*NumPy does not actually copy B. It just “pretends” to repeat it, which saves memory and makes the operation fast.*


In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([10, 20, 30])

result = A + B

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


Que:3 What are missing values in Pandas and how are they represented?
Create a DataFrame with missing values and write code to:

• Detect missing values

• Replace them with the column mean

Explain each step.

Answer: 

**Missing values in Pandas:**  Missing values represent unavailable or undefined data.

**Representation of missing values:**
1. NaN (not a number)
2. None
3. NaT (for datetime)

In [ ]:
import pandas as pd # Importing the pandas library
import numpy as np # Importing the NumPy library

data = {
    "Student": ["Rahul", "Anita", "John", "Sara", "Mike"],
    "Marks": [85, np.nan, 78, 92, np.nan],
    "Attendance": [90, 88, np.nan, 95, 80]
}
# Create a DataFrame from the dictionary
df = pd.DataFrame(data) # Display the DataFrame
print(df) 


  Student  Marks  Attendance
0   Rahul   85.0        90.0
1   Anita    NaN        88.0
2    John   78.0         NaN
3    Sara   92.0        95.0
4    Mike    NaN        80.0


Que:4. Explain boolean indexing in NumPy or Pandas.

Create a DataFrame with at least 5 columns and filter rows based on two conditions
using logical operators. Explain how filtering works internally.


Answer: 

**Boolean Indexing :**
*Boolean indexing is a method used in NumPy and Pandas to filter data using conditions.*

*When we apply a condition, it returns True or False values.Only the elements or rows where the condition is True are selected.*

- In NumPy, boolean indexing selects elements from an array based on a condition.
- In Pandas, it is used to filter rows in a DataFrame.

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
result = arr[arr > 25] # It filters the array to include only elements greater than 25
print(result)

[30 40 50]


In [10]:
import pandas as pd
data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [60, 80, 75, 50]
}

df = pd.DataFrame(data)

result = df[df["Marks"] > 70] # It filters the DataFrame to include only rows where the "Marks" column has values greater than 70

print(result)

  Name  Marks
1    B     80
2    C     75


Que:5 What is the purpose of the groupby() function in Pandas?

Create a DataFrame with categorical data (e.g., department & salary) and calculate
the average salary per department using groupby(). Explain the output

Answer: 
*The groupby() function is used to group data based on one or more columns and then perform calculations on each group.*

**groupby() function:** It follows the *Split → Apply → Combine*
- Splits data into gropus
- Applies a function such as mean, sum, count.
- Combines result



In [ ]:
import pandas as pd
data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [60, 80, 75, 50]
}
df = pd.DataFrame(data)
result= df.groupby("Marks")["Name"].count()
# It groups the DataFrame by the "Marks" column and counts the number of occurrences of each unique mark

print(result)

Marks
50    1
60    1
75    1
80    1
Name: Name, dtype: int64
