### NumPy


NumPy means Numerical Python. It is powershell python libarary which is used for numbers, arrays, and mathematical operations. 
It is a backbone of Data Science, Machine Learning and Scientific Computing

#### installation of numpy


In [ ]:
! pip install numpy

In [ ]:
#importing the numpy library
import numpy as np 

In [4]:
# creating a 1D array of random numbers
arr = np.random.random(10)

In [ ]:
# displaying the array
arr

array([0.79705636, 0.21070766, 0.91083422, 0.9536658 , 0.7573811 ,
       0.72043248, 0.54199144, 0.32244942, 0.35174748, 0.55195862])

### Array Attributes

In [ ]:
# creating a 1D array of numbers from 0 to 59
arr=np.arange(60) # arange is used to create an array of numbers from 0 to n-1

In [ ]:
# reshaping the array to 12 rows and 5 columns
arr = arr.reshape(12,5)

In [ ]:
# displaying the array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
print("shape of the array is ", arr.shape) # shape is used to get the number of rows and columns in the array
print("data type of the array is ", arr.dtype) # dtype is used to get the data type of the array
print("number of dimensions of the array is ", arr.ndim) # ndim is used to get the number of dimensions of the array
print("size of the array is ", arr.size) # size is used to get the total number of elements in the array

ahape of the array is  (12, 5)
data type of the array is  int64
number of dimensions of the array is  2
size of the array is  60


In [ ]:
arr[1] # indexing the array to get the second row of the array

array([5, 6, 7, 8, 9])

In [ ]:
arr[1][3] # indexing the array to get the element in the second row and fourth column of the array

np.int64(8)

In [ ]:
arr[-11][-1] # indexing the array to get the element in the second row and fourth column of the array using negative indexing

np.int64(9)

In [ ]:
arr[11,4] # indexing the array to get the element in the last row and last column of the array using negative indexing

np.int64(59)

In [ ]:
arr[-1,-1]=20 #

In [ ]:
arr # displaying the array after changing the last element to 20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 20]])

In [ ]:
arr.T # transposing the array to get the columns as rows and rows as columns

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 20]])

### convertion of arrays 

In [ ]:
arr=arr.flatten() # flattening the array to get a 1D array from a 2D array

In [ ]:
arr # displaying the flattened array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 20])

In [ ]:
print("shape of the array is ", arr.shape) # shape is used to get the number of rows and columns in the array
print("data type of the array is ", arr.dtype) # dtype is used to get the data type of the array
print("number of dimensions of the array is ", arr.ndim) # ndim is used to get the number of dimensions of the array
print("size of the array is ", arr.size) # size is used to get the total number of elements in the array

shape of the array is  (60,)
data type of the array is  int64
number of dimensions of the array is  1
size of the array is  60


In [ ]:
arr=np.arange(225).reshape(5,15,3) # creating a 3D array of numbers from 0 to 224 and reshaping it to 5 layers, 15 rows and 3 columns

In [ ]:
arr # displaying the flattened array

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [ ]:
arr[0] # indexing the array to get the first layer of the 3D array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[0,0,1] # indexing the array to get the element in the first layer, first row and second column of the 3D array

np.int64(1)

In [ ]:
arr[0:4,0:3,0:2] # slicing the array to get the first 4 layers, first 3 rows and first 2 columns of the 3D array

array([[[  0,   1],
        [  3,   4],
        [  6,   7]],

       [[ 45,  46],
        [ 48,  49],
        [ 51,  52]],

       [[ 90,  91],
        [ 93,  94],
        [ 96,  97]],

       [[135, 136],
        [138, 139],
        [141, 142]]])

In [ ]:
arr[0:4,0,0] # slicing the array to get the first 4 layers, first row and first column of the 3D array

array([  0,  45,  90, 135])

In [ ]:
arr[0:5,0:5,0:3] # slicing the array to get the first 5 layers, first 5 rows and first 3 columns of the 3D array

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143],
        [144, 145, 146],
        [147, 148, 149]],

       [[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188],
        [189, 190, 191],
        [192, 193, 194]]])

In [ ]:
arr[0:4][0][0] # slicing the array to get the first 4 layers, first row and first column of the 3D array using multiple indexing

array([0, 1, 2])

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10]) # creating a 1D array of numbers from 1 to 10
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]) # creating another 1D array of numbers from 1 to 10
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])  # creating another 1D array of numbers from 1 to 10

In [ ]:
arr+2 # adding 2 to each element of the array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr*2 # multiplying each element of the array by 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr1/arr2 # dividing each element of the first array by the corresponding element of the second array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr1-arr2 # subtracting each element of the second array from the corresponding element of the first array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr1+arr2 # adding each element of the first array to the corresponding element of the second array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr**2 # raising each element of the array to the power of 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr.sort() # sorting the array in ascending order